/*
 * 	Template:		This code was generated by the Coder Journal [http://www.coderjournal.com] Data Layer Template.
 * 	Created On :	8/27/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

using System;
using System.Collections.Generic;
using System.Text;

namespace CoderJournal.Modules.Journal.Data
{
	public interface ITable<T>
	{
		T PrimaryKey { get; }
		void CommitChanges();
	}
}
