/*
 * 	Template:		This code was generated by the Coder Journal [http://www.coderjournal.com] Data Layer Template.
 * 	Created On :	8/27/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

using System;
using System.Collections.Generic;
using System.Text;

namespace CoderJournal.Modules.Journal.Data
{
	public class TableCollection<TKey, TValue> : List<TValue>
		where TValue : ITable<TKey>, new()
	{
		public TValue this[TKey primaryKey]
		{
			get
			{
				foreach (TValue entity in this)
					if (entity.PrimaryKey.Equals(primaryKey))
						return entity;

				return new TValue();
			}
		}

		public void CommitChanges()
		{
			foreach (TValue entity in this)
				entity.CommitChanges();
		}
	}
}