/*
 * 	Template:		This code was generated by the Coder Journal [http://www.coderjournal.com] Data Layer Template.
 * 	Created On :	8/24/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'Journal')
	begin
		print 'Dropping Procedure Journal'
		drop procedure Journal
	end
go

print 'Creating Procedure Journal'
go

create procedure Journal
(
	@JournalID as uniqueidentifier = null,
	@Title as varchar(75),
	@Summary as varchar(350),
	@Updated as datetime,
	@Published as datetime,
	@Content as text
)
as

--	Author:		Coder Journal [http://www.coderjournal.com]
--	Date:		8/24/2006
--	Purpose:	Inserts or updates an entity into Journal.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [Journal] 
	where 
		[JournalID] = @JournalID
) begin

	update 
		[Journal]
	
	set
		[JournalID] = @JournalID,
		[Title] = @Title,
		[Summary] = @Summary,
		[Updated] = @Updated,
		[Published] = @Published,
		[Content] = @Content
	
	where
		[JournalID] = @JournalID

end else begin

	insert into [Journal] (
		[JournalID],
		[Title],
		[Summary],
		[Updated],
		[Published],
		[Content]
	) values (
		@JournalID,
		@Title,
		@Summary,
		@Updated,
		@Published,
		@Content
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'Journal_Delete')
	begin
		print 'Dropping Procedure Journal_Delete'
		drop procedure Journal_Delete
	end
go

print 'Creating Procedure Journal_Delete'
go

create procedure Journal_Delete
(
	@JournalID as uniqueidentifier
)
as

--	Author:		Coder Journal [http://www.coderjournal.com]
--	Date:		8/24/2006
--	Purpose:	Delete the entity in Journal.

delete from 
	[Journal]

where
	[JournalID] = @JournalID

go

set nocount off