/*
 * 	Template:		This code was generated by the Coder Journal [http://www.coderjournal.com] Data Layer Template.
 * 	Created On :	8/24/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'JournalTagLink')
	begin
		print 'Dropping Procedure JournalTagLink'
		drop procedure JournalTagLink
	end
go

print 'Creating Procedure JournalTagLink'
go

create procedure JournalTagLink
(
	@JournalID as uniqueidentifier = null,
	@TagID as int = null
)
as

--	Author:		Coder Journal [http://www.coderjournal.com]
--	Date:		8/24/2006
--	Purpose:	Inserts or updates an entity into JournalTagLink.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [JournalTagLink] 
	where 
		[JournalID] = @JournalID
		and [TagID] = @TagID
) begin

	update 
		[JournalTagLink]
	
	set
		[JournalID] = @JournalID,
		[TagID] = @TagID
	
	where
		[JournalID] = @JournalID
		and [TagID] = @TagID

end else begin

	insert into [JournalTagLink] (
		[JournalID],
		[TagID]
	) values (
		@JournalID,
		@TagID
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'JournalTagLink_Delete')
	begin
		print 'Dropping Procedure JournalTagLink_Delete'
		drop procedure JournalTagLink_Delete
	end
go

print 'Creating Procedure JournalTagLink_Delete'
go

create procedure JournalTagLink_Delete
(
	@JournalID as uniqueidentifier,
	@TagID as int
)
as

--	Author:		Coder Journal [http://www.coderjournal.com]
--	Date:		8/24/2006
--	Purpose:	Delete the entity in JournalTagLink.

delete from 
	[JournalTagLink]

where
	[JournalID] = @JournalID
	and [TagID] = @TagID

go

set nocount off