/*
 * 	Template:		This code was generated by the Coder Journal [http://www.coderjournal.com] Data Layer Template.
 * 	Created On :	8/27/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'Journal_Link')
	begin
		print 'Dropping Procedure Journal_Link'
		drop procedure Journal_Link
	end
go

print 'Creating Procedure Journal_Link'
go

create procedure Journal_Link
(
	@LinkID as int = null,
	@JournalID as uniqueidentifier,
	@Href as varchar(255),
	@Title as varchar(75),
	@Relationship as varchar(50),
	@Type as varchar(50)
)
as

--	Author:		Coder Journal [http://www.coderjournal.com]
--	Date:		8/27/2006
--	Purpose:	Inserts or updates an entity into Link.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [Link] 
	where 
		[LinkID] = @LinkID
) begin

	update 
		[Link]
	
	set
		[LinkID] = @LinkID,
		[JournalID] = @JournalID,
		[Href] = @Href,
		[Title] = @Title,
		[Relationship] = @Relationship,
		[Type] = @Type
	
	where
		[LinkID] = @LinkID

end else begin

	insert into [Link] (
		[LinkID],
		[JournalID],
		[Href],
		[Title],
		[Relationship],
		[Type]
	) values (
		@LinkID,
		@JournalID,
		@Href,
		@Title,
		@Relationship,
		@Type
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'Journal_Link_Delete')
	begin
		print 'Dropping Procedure Journal_Link_Delete'
		drop procedure Journal_Link_Delete
	end
go

print 'Creating Procedure Journal_Link_Delete'
go

create procedure Journal_Link_Delete
(
	@LinkID as int
)
as

--	Author:		Coder Journal [http://www.coderjournal.com]
--	Date:		8/27/2006
--	Purpose:	Delete the entity in Link.

delete from 
	[Link]

where
	[LinkID] = @LinkID

go

set nocount off