/*
 * 	Template:		This code was generated by the Coder Journal [http://www.coderjournal.com] Data Layer Template.
 * 	Created On :	8/24/2006
 * 	Remarks:		Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

set nocount on

--------------------------------------------------------------------------------------------
--	Insert or Update entity
--------------------------------------------------------------------------------------------

if exists (select * from sysobjects where type = 'P' and name = 'User')
	begin
		print 'Dropping Procedure User'
		drop procedure User
	end
go

print 'Creating Procedure User'
go

create procedure User
(
	@UserID as int = null,
	@Email as varchar(50),
	@Password as varchar(255),
	@Name as varchar(50),
	@Link as varchar(255)
)
as

--	Author:		Coder Journal [http://www.coderjournal.com]
--	Date:		8/24/2006
--	Purpose:	Inserts or updates an entity into User.

-- check to make sure the record already doesn't exisit
if exists (	
	select *
	from [User] 
	where 
		[UserID] = @UserID
) begin

	update 
		[User]
	
	set
		[UserID] = @UserID,
		[Email] = @Email,
		[Password] = @Password,
		[Name] = @Name,
		[Link] = @Link
	
	where
		[UserID] = @UserID

end else begin

	insert into [User] (
		[UserID],
		[Email],
		[Password],
		[Name],
		[Link]
	) values (
		@UserID,
		@Email,
		@Password,
		@Name,
		@Link
	)

end

go

--------------------------------------------------------------------------------------------
--	Delete entity
--------------------------------------------------------------------------------------------
if exists (select * from sysobjects where type = 'P' and name = 'User_Delete')
	begin
		print 'Dropping Procedure User_Delete'
		drop procedure User_Delete
	end
go

print 'Creating Procedure User_Delete'
go

create procedure User_Delete
(
	@UserID as int
)
as

--	Author:		Coder Journal [http://www.coderjournal.com]
--	Date:		8/24/2006
--	Purpose:	Delete the entity in User.

delete from 
	[User]

where
	[UserID] = @UserID

go

set nocount off